sudo: false
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

install: echo "skip bundle install"

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - berks install

script:
  - rubocop
  - foodcritic -f any -t ~FC016 -X spec .
  - rspec --color --format progress
